package com.gqy.analysis_code.dao;

import com.gqy.analysis_code.entity.Edge;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface EdgeMapper {

    List<Edge> selectBynode(@Param("targetid") Integer targetid, @Param("sourceid") Integer sourceid);
    List<Edge> selectall();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edge
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edge
     *
     * @mbggenerated
     */
    int insert(Edge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edge
     *
     * @mbggenerated
     */
    Edge selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edge
     *
     * @mbggenerated
     */
    List<Edge> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edge
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Edge record);
}