package com.gqy.analysis_code.entity;

import java.io.Serializable;

public class Classnode implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classnode.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classnode.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classnode.fullname
     *
     * @mbggenerated
     */
    private String fullname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classnode.calleeTimes
     *
     * @mbggenerated
     */
    private Integer calleetimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classnode.callerTimes
     *
     * @mbggenerated
     */
    private Integer callertimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table classnode
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classnode.id
     *
     * @return the value of classnode.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classnode.id
     *
     * @param id the value for classnode.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classnode.name
     *
     * @return the value of classnode.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classnode.name
     *
     * @param name the value for classnode.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classnode.fullname
     *
     * @return the value of classnode.fullname
     *
     * @mbggenerated
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classnode.fullname
     *
     * @param fullname the value for classnode.fullname
     *
     * @mbggenerated
     */
    public void setFullname(String fullname) {
        this.fullname = fullname == null ? null : fullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classnode.calleeTimes
     *
     * @return the value of classnode.calleeTimes
     *
     * @mbggenerated
     */
    public Integer getCalleetimes() {
        return calleetimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classnode.calleeTimes
     *
     * @param calleetimes the value for classnode.calleeTimes
     *
     * @mbggenerated
     */
    public void setCalleetimes(Integer calleetimes) {
        this.calleetimes = calleetimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classnode.callerTimes
     *
     * @return the value of classnode.callerTimes
     *
     * @mbggenerated
     */
    public Integer getCallertimes() {
        return callertimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classnode.callerTimes
     *
     * @param callertimes the value for classnode.callerTimes
     *
     * @mbggenerated
     */
    public void setCallertimes(Integer callertimes) {
        this.callertimes = callertimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classnode
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", fullname=").append(fullname);
        sb.append(", calleetimes=").append(calleetimes);
        sb.append(", callertimes=").append(callertimes);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}